### ISSUE TITLE
continue autocompleting after insertion

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [lisps/plugin-linksuggest#2]
Hi,

on the plugin page you write "Just hit ''STRG'' or ''SHIFT'' and the search will begin."

In my wiki installation it works only if both the ''STRG'' and ''SHIFT'' buttons are pressed together! So why doesn't the autocomplete continue automatically after inserting a (sub-)namespace until the wanted page is reached? 

Regards 
Juergen

**Comment by ferluszt** [comment]
technically it should start searching after each selection of a namespace. 

the problem has to be related to the used textcomplete plugin or browser or os. 

Actually textcomplete will start its search on every keyup event.

are you using the recent version from github?

**Comment by Juergen-aus-Koeln** [comment]
Yes I have just installed the current version available at dokuwiki, and I've tested it with firefox and IE11.

**Comment by ferluszt** [comment]
can you try it again with the master branch from github

**Comment by Juergen-aus-Koeln** [comment]
Thank you very much, after touching the configuration files it works perfectly
