### ISSUE TITLE
Drop down menu

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [lisps/plugin-linksuggest#3]
Hi,

when using the template bootstrap3, the drop down menu for the user-actions is too small to see all possible entries, for example for editing, without scrolling:
![fehler](https://cloud.githubusercontent.com/assets/1800472/8429713/9acc1f6c-1f2a-11e5-8f11-a07f60ace5f7.png)

I have a cross reference as issue for the template "bootstrapper3", see https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/42

Best regards
Juergen

**Comment by peterfromearth** [comment]
sorry for the long delay
